--Creando base de datos
CREATE DATABASE CasosDenuncias;
GO

USE CasosDenuncias
GO

-- Dimensión Lugar:
CREATE  TABLE LUGAR (
ID_LUGAR INT NOT NULL,
UBIGEO VARCHAR(50) NOT NULL,
NOMBREDD NVARCHAR (150) NOT NULL,
NOMBREPP NVARCHAR (150) NOT NULL,
NOMBREDI NVARCHAR (150) NOT NULL,
VIA VARCHAR(150) NOT NULL,
CONSTRAINT PK_LUGAR
PRIMARY KEY CLUSTERED (ID_LUGAR ASC)
);


-- Dimensión tipo:
CREATE TABLE TIPO (
ID_TIPO INT NOT NULL,
DELITO_GENERICO NVARCHAR(250) NOT NULL,
DELITO_ESPECIFICO NVARCHAR(250) NOT NULL,
DELITO_MODALIDAD NVARCHAR(250) NOT NULL,
CONSTRAINT PK_TIPO 
PRIMARY KEY CLUSTERED (ID_TIPO ASC)
);


-- Dimensión victimas
CREATE TABLE VICTIMAS (
ID_VICTIMAS INT NOT NULL,
SEXO VARCHAR(50) NOT NULL,
EDAD INT NOT NULL,
TOTAL_VICTIMAS INT NOT NULL,
CONSTRAINT PK_EDAD
PRIMARY KEY CLUSTERED (ID_VICTIMAS ASC)
);


-- Dimensión tiempo:
CREATE TABLE TIEMPO (
ID_TIEMPO INT NOT NULL,
DIA INT NOT NULL,
MES VARCHAR(50) NOT NULL,
ANIO INT NOT NULL,
HOR NVARCHAR(50) NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT PK_TIEMPO 
PRIMARY KEY CLUSTERED (ID_TIEMPO ASC)
);

-- Tabla de hechos: denuncia:
CREATE TABLE DENUNCIAS(
ID_VICTIMAS INT NOT NULL,
ID_LUGAR INT NOT NULL,
ID_TIEMPO INT NOT NULL,
ID_TIPO INT NOT NULL,
CONSTRAINT FK_DENUNCIAS_VICTIMAS FOREIGN KEY (ID_VICTIMAS)
REFERENCES VICTIMAS (ID_VICTIMAS),
CONSTRAINT FK_DENUNCIAS_LUGAR FOREIGN KEY (ID_LUGAR)
REFERENCES LUGAR (ID_LUGAR),
CONSTRAINT FK_DENUNCIAS_TIEMPO FOREIGN KEY (ID_TIEMPO)
REFERENCES TIEMPO (ID_TIEMPO),
CONSTRAINT FK_DENUNCIAS_TIPO FOREIGN KEY (ID_TIPO)
REFERENCES TIPO (ID_TIPO));

